services:
  transaction-db:
    image: postgres:16
    container_name: transaction-db-container
    environment:
      POSTGRES_DB: transaction_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5434:5432"  # Fora da sua máquina bate na 5434, dentro do container usa a 5432 padrão
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d transaction_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  transaction_data: